run:
  go: '1.22.2'

fix: true

output:
  formats:
    - format: json
      path: stderr
    - format: checkstyle
      path: report.xml
    - format: colored-line-number

linters:
  enable-all: true
  disable:
    - bodyclose
    - containedctx
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gomoddirectives
    - gomnd
    - ireturn
    - lll
    - mnd
    - nestif
    - nonamedreturns
    - stylecheck
    - revive
    - wrapcheck